name: Trivy Scan - nginx:latest

on: [workflow_dispatch]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run Trivy scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy image --severity CRITICAL nginx:latest > result.txt
            cat result.txt

      - name: Check for critical vulnerabilities
        run: |
          if grep -q "CRITICAL" result.txt; then
            echo "Critical vulnerabilities found!"
          else
            echo "No critical vulnerabilities found. Scan successful."
          fi
